import pandas as pd
import pickle
from mcc_sussex import PROJECT_DIR


def esco_occupations() -> pd.DataFrame:
    """gets URI, description, and associated metadata for each ESCO occupation

    Returns:
        pd.DataFrame: dataframe with metadata about each ESCO occupation
    """
    return pd.read_csv(f"{PROJECT_DIR}/mcc_sussex/data/processed/ESCO_occupations.csv")


def esco_skills() -> pd.DataFrame:
    """gets URI, description, and associated metadata for each ESCO skill

    Returns:
        pd.DataFrame:  dataframe with metadata about each ESCO skill
    """
    return pd.read_csv(f"{PROJECT_DIR}/mcc_sussex/data/processed/ESCO_skills.csv")


def esco_occuptions_to_skills() -> pd.DataFrame:
    """gets mapping of all skills to ESCO occupations

    Returns:
        pd.DataFrame: mapping of ESCO skills to occupations. 
    """
    return pd.read_csv(f"{PROJECT_DIR}/mcc_sussex/data/processed/ESCO_ocupation_To_skills.csv")


def esco_occupation_ids() -> pd.DataFrame:
    """gets lookup of ids for esco occupations generated from data_preprocessing/esco_ids.py

    Returns:
        pd.DataFrame: lookup of ESCO occupation concept URIs to ids
    """
    return pd.read_csv(f"{PROJECT_DIR}/mcc_sussex/data/processed/esco_ids.csv")


def esco_skill_ids() -> pd.DataFrame:
    """gets lookup of ids for esco skills generated from data_preprocessing/esco_skill_ids.py

    Returns:
        pd.DataFrame: lookup of ESCO skill concept URIs to ids
    """
    return pd.read_csv(f"{PROJECT_DIR}/mcc_sussex/data/processed/esco_skill_ids.csv")


def esco_skill_hierarchy() -> pd.DataFrame:
    """lookup of all ESCO skill leves to occupations

    Returns:
        pd.DataFrame: lookup of all ESCO skill leves to occupations
    """
    return pd.read_csv(f"{PROJECT_DIR}/mcc_sussex/data/interim/esco_data_formatted.csv")


def esco_essential_skills_lookup() -> pd.DataFrame:
    """gets lookup of all ESCO occupations to essential skills generated by data_preprocessing/generate_occupation_skills_dataframes.py

    Returns:
        pd.DataFrame: lookup of all ESCO occupations to essential skills
    """
    return pickle.load(open(f"{PROJECT_DIR}/mcc_sussex/data/processed/occupation_to_essential_skills.pickle", 'rb'))


def esco_optional_skills_lookup() -> pd.DataFrame:
    """gets lookup of all ESCO occupations to optional skills generated by data_preprocessing/generate_occupation_skills_dataframes.py

    Returns:
        pd.DataFrame: lookup of all ESCO occupations to optional skills
    """
    return pickle.load(open(f"{PROJECT_DIR}/mcc_sussex/data/processed/occupation_to_essential_skills.pickle", 'rb'))


def esco_all_skills_lookup() -> pd.DataFrame:
    """gets lookup of all ESCO occupations to  skills generated by data_preprocessing/generate_occupation_skills_dataframes.py

    Returns:
        pd.DataFrame: lookup of all ESCO occupations to all skills
    """
    return pickle.load(open(f"{PROJECT_DIR}/mcc_sussex/data/processed/occupation_to_all_skills.pickle", 'rb'))


def level_2_skills() -> pd.DataFrame:
    """returns lookup of ESCO occupations to skills in level 2 of the skills hierarchy created via data_preprocessing/skills_hierarchy.py

    Returns:
        pd.DataFrame: ESCO occupations to level 2 skills 
    """
    return pd.read_csv(f"{PROJECT_DIR}/mcc_sussex/data/processed/level_2_hierarchy.csv")


def level_3_skills() -> pd.DataFrame:
    """returns lookup of ESCO occupations to skills in level 3 of the skills hierarchy created via data_preprocessing/skills_hierarchy.py

    Returns:
        pd.DataFrame: ESCO occupations to level 3 skills 
    """
    return pd.read_csv(f"{PROJECT_DIR}/mcc_sussex/data/processed/level_3_hierarchy.csv")
